Add Windows support for File and Service modules
pytest-dev/pytest-testinfra pull request #683
Opened 2023-02-12 06:19 UTC by tdas3001

Opened a new PR for adding Windows support for File and Service modules in Testinfra as the old one  #532 has been inactive for quite some time. The PR contains all the changes in #532 and a few more implementations.

```py
# Basic file and service operations are now supported in windows remote server
>>> host.file("C:/Users/Administrator/pytest-testinfra").is_directory
True
>>> host.file("C:/Users/Administrator/pytest-testinfra/images").listdir()
['alphine', 'archlinux', 'debian_bullseye', 'rockylinux8', 'ubuntu_xenial']

```
Please let me know of any comments.

2023-02-13 08:04 UTC, tdas3001 commented
@philpep feel free to have a look at the PR

2023-05-19 07:16 UTC, philpep requested changes
Thanks! Like I said in some other PR, I don't have knowledge neither time to maintain this. However this PR looks almost reasonable, so if other windows user can test this and tell me it's useful for them, I'll be happy to merge it.

2023-05-19 07:16 UTC, philpep commented on testinfra/modules/file.py
> +import six
```suggestion
```

2023-05-19 07:16 UTC, philpep commented on testinfra/modules/file.py
> +        """
```suggestion
```

2023-05-19 07:16 UTC, philpep commented on testinfra/modules/file.py
> +        """
```suggestion
```

2023-05-19 07:16 UTC, philpep commented on testinfra/modules/file.py
> +            raise RuntimeError("Unexpected output %s" % (out,))
```suggestion
        out = self.run_expect([0], r"powershell -command \"cat -- '%s'\"", self.path)
```

2023-05-19 07:16 UTC, philpep commented on testinfra/modules/file.py
> +        return [item.strip() for item in out.stdout.strip().split("\n")]
```suggestion
        out = self.check_output(
            r"powershell -command \"Get-ChildItem -Path '%s' | Select-Object -ExpandProperty Name\"",
            self.path,
        )
        return [item.strip() for item in out.strip().split("\n")]
```

2023-05-19 07:16 UTC, philpep commented on testinfra/modules/file.py
> +        return not self.__eq__(other)
```suggestion
```

(this is already defined in parent class)

2023-05-19 07:16 UTC, philpep commented on testinfra/modules/service.py
> +                "Get-Service '%s' | Select -ExpandProperty Status",  # noqa: E501
```suggestion
                "Get-Service '%s' | Select -ExpandProperty Status",
```

useless noqa ?

2023-05-19 07:16 UTC, philpep commented on testinfra/modules/service.py
> +                "Get-Service '%s' | Select -ExpandProperty StartType",  # noqa: E501
```suggestion
                "Get-Service '%s' | Select -ExpandProperty StartType",
```

useless noqa ?

2023-05-19 13:38 UTC, tdas3001 commented
> Thanks! Like I said in some other PR, I don't have knowledge neither time to maintain this. However this PR looks almost reasonable, so if other windows user can test this and tell me it's useful for them, I'll be happy to merge it.

Thanks for your comments @philpep . I would get back to them asap!

2023-05-20 07:17 UTC, philpep approved these changes

2023-05-20 07:17 UTC, merged

2023-05-20 07:18 UTC, philpep commented
Merged, thanks!