Replace crypt with passlib in testing
pytest-dev/pytest-testinfra pull request #764
Opened 2024-05-07 13:57 UTC by martinhoyer

crypt module is being deprecated in Python 3.13. It would be nice to switch to hashlib or passib. (hashlib being built-in)

2024-05-07 14:35 UTC, martinhoyer commented
as for the CI failure, the new version of Salt requires timelib and that does fails to build. Installing gcc or locking salt version could help?

2024-05-26 09:20 UTC, martinhoyer commented
Any chance someone could take look please?

2024-05-26 14:45 UTC, philpep approved these changes

2024-05-26 15:09 UTC, philpep requested changes
Looks test is failing. Even with passlib.hosts.linux_context.verify(). Maybe hash algorithm is not handled by passlib ?

2024-05-26 15:17 UTC, martinhoyer commented
> Looks test is failing. Even with passlib.hosts.linux_context.verify(). Maybe hash algorithm is not handled by passlib ?

Thanks for looking into it. Checking what's wrong.

2024-05-26 17:13 UTC, martinhoyer commented
ok, turns out it's not as easy as I thought. `crypt.crypt()` does not have a replacement in Python and spwd was also deprecated in 3.13. How would you like to proceed?

2024-05-27 05:35 UTC, philpep commented
> ok, turns out it's not as easy as I thought. `crypt.crypt()` does not have a replacement in Python and spwd was also deprecated in 3.13. How would you like to proceed?

I think we can just assert `host.user().password` startswith `$` and eventually has some expected `len()`. IIRC this should be constant, whereas encrypted password value might change between docker builds due do some random hash.

2024-05-27 12:13 UTC, philpep approved these changes

2024-05-27 12:18 UTC, merged